### ISSUE TITLE
Safe for production?

### ISSUE THREAD

**Issue by dhaavi** [rot256/pblind#1]
Hey @rot256, this is some very nice work!

We are looking for a bling ecc signature library that we can use for anonymized authorization in [a VPN-like service](https://safing.io/spn/).
Yours seems to be the best for our use case and most trustworthy I could find so far.

While you have a notice about API stability, you do not mention if you deem this library safe to use in production.
So, just to be on the safe side here, I wanted to get in contact before using it.

Thanks!

**Comment by rot256** [comment]
It's been a while since I work on this, but security wise the library strives to be production quality. 

Meaning standard pitfalls are taken care of, e.g.

- Point on curve checks
- Constant time curve arithmetic
- Cryptographically secure random

However, I make no guarantees.  Two things to be aware of in production:

- hashToPoint, used to hash the info to a point is not constant time. This however should not be a problem: "info" is public information known to the signer.

- As with many blind signature schemes beware of ROS attacks https://eprint.iacr.org/2020/945.pdf, where an adversary can create multiple blind signatures e.g. signing n + 1 messages by starting n parallel sessions.  This attack applies to a wide range of blind signatures with more than 2 rounds of interaction (including Abe-Okamoto, see sec. 6.3.1 of the paper) and can only really be mitigated by not allowing parallel sessions for the same public key, meaning you must finish/time-out a signing session with one client before allowing another one to attempt signing.

**Comment by dhaavi** [comment]
Thank you very much for your answer.

> It's been a while since I work on this, but security wise the library strives to be production quality.

Great!

> However, I make no guarantees.

We fully understand and also do not expect this. We are thinking about having this audited in the mid-term future in order ensure everything is in order. When the time comes, I'll contact you to see if and how you would want to participate in an audit, if this is ok for you.

> * hashToPoint, used to hash the info to a point is not constant time.

Thanks. Will keep this in mind.

> * As with many blind signature schemes beware of ROS attacks.

Thanks a lot for this vital hint. If I understand correctly, this only applies if the info is static. So, if we include a nonce in the info, then this should be mitigated, correct?

**Comment by rot256** [comment]
> Thanks a lot for this vital hint. If I understand correctly, this only applies if the info is static. So, if we include a nonce in the info, then this should be mitigated, correct?

I believe so (no sure if the security reduction is in this model), however, it would then be completely linkable if you use a unique nonce...

**Comment by dhaavi** [comment]
> I believe so (no sure if the security reduction is in this model), however, it would then be completely linkable if you use a unique nonce...

Yes, that is true - going think about this more.
Thank you for your time and thoughts on this.

**Comment by dhaavi** [comment]
I just saw that you did some improvements yesterday and switched to go modules. Awesome! 👌 Thanks!
